# config.py

import os

BINANCE_API_KEY = os.getenv("cyF4T8OTEomDm5L8nBX9AweNjOwkLWoObDn8uzlhSSpwS0MuFtyJGEaIe283bSQZ")
BINANCE_API_SECRET = os.getenv("NhKbFEuTVe9TXVa9fuj0Q2JJP1af5dfjuII3oMJ7uRp5ZhtrTwTi60tL5VJn0Bkf")

SYMBOL = "ETHUSDC"
QUOTE_ASSET = "USDC"
BASE_ASSET = "ETH"

TRADE_PERCENTAGE = 0.04
MAX_ENTRIES_PER_GAP = 3

WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")
